#!/bin/bash
new_count=`mysqladmin -udba -pcntv.cn -h$1 extended-status |awk -F'|' '/Table_locks_waited/{print $3}'`
for loop in $1
do
outfile=/usr/local/nagios/tmpfile/tlock-$1.out
if [ ! -e $outfile ];then
sudo make -p $outfile
sudo chmod 777 $outfile
fi
if [ -s $outfile ];then
last_count="0"
else
last_count=`cat $outfile`
fi
count=`expr $new_count - $last_count`
if [ $count -lt '5' ];then
echo "OK - table lock count is $count"
exit 0
elif [ `expr $start - $end` -eq '5' ];then
echo "WARNING - table lock count is $count"
exit 1
elif [ `expr $start - $end` -ge '5' ];then
echo "WARNING - table lock count is $count"
exit 2
fi
mysqladmin -udba -pcntv.cn -h$1 extended-status |awk -F'|' '/Table_locks_waited/{print $3}' > $outfile
done
