#!/bin/bash
ST_OK=0
ST_CR=2

wget -S -o /tmp/xiyou-api.out http://my.cntv.cn/
cat /tmp/xiyou-api.out | grep "HTTP/1.1" > /dev/null
if [ $? -eq "0" ];then
echo "xiyou api OK."
exit $ST_OK
else
echo "xiyou api Failed!"
exit $ST_CR
fi
